### ISSUE TITLE
Is there a way to change clothes for saved human?

### ISSUE THREAD

**Issue by xand00** [NitroxNova/Humanizer#11]
i want to do clothes swap for human models, but i don't know if plugin allows such thing during runtime, i tried to run project(F5) with humanizer.gd node, at first it said that HumanizerGlobalConfig.config is null when script res://addons/humanizer/scripts/resources/human_body_part.gd tried to access HumanizerGlobalConfig.config.body_part_slots at 7th line, after that any tries to run project led to crash without logs

so, is there a way to:
- run game with humanizer.gd node and swap clothes?
- run game with saved human and swap clothes?

My godot version is 4.2.1 stable

**Comment by matt-seaton** [comment]
It can be done but it is slow.  The whole human has to be re-built from scratch by the humanizer script.  You just create a humanizer node and set it's human_config to load a previously saved human, then make any changes you want.  I would recommend doing it in a background thread so as to not lock the main thread and use a signal to let you know when it's finished.  I can add some signals for this.  Don't expect it to be very fast.  It may take 10-20 seconds to do everything.

HumanizerGlobalConfig.config should never be null.  Try to pull the latest commit and either restart the project or disable and re-enable the plugin.  Let me know if this error persists.

**Comment by xand00** [comment]
Error no longer persists

i'm testing approach you said (setting human_config)

Structure in scene:
![image](https://github.com/NitroxNova/Humanizer/assets/32330527/f1e16f83-185a-40a8-ae9d-3ae7bf7fbc6c)

When this code runs:
![image](https://github.com/NitroxNova/Humanizer/assets/32330527/d1549153-ae87-4b22-9f40-ed2983a54160)

This error appears:
![image](https://github.com/NitroxNova/Humanizer/assets/32330527/073d308c-a403-4953-bb91-3d9cc24d0834)

I tried to print mesh, but in console it says Object#null, i guess code expects that Humanizer node has %ClothingName% child node, but it does not have it and errors appears

**Comment by xand00** [comment]
I misunderstood you, it turns out I should have created Humanizer node during runtime, not before starting game

**Comment by matt-seaton** [comment]
ok i pushed a new commit.  see if that fixes your issue

**Comment by xand00** [comment]
It didn't fix issue when scene has Humanizer before starting game, but it worked before and works now when i create Humanizer during runtime

**Comment by matt-seaton** [comment]
ok for some reason the hair color is being set before the hair mesh is instanced.  ill have to track that down.  it shouldn't matter when the humanizer node is instanced.  it should not be in the scenetree though if you want to use background threads.

**Comment by xand00** [comment]
yes, it will be better if it will not matter when to instantiate humanizer node

i got it working, my clothes change, it's also kinda slow as you said, but it's too late for me here, i'll try to add this to threads after sleep

**Comment by matt-seaton** [comment]
we are planning to offload some of the slower processes to compute shaders soon so hopefully it will be faster

**Comment by xand00** [comment]
for some reason threads didn't help, main thread is still being blocked when i call `apply_clothes`, i do it like this:
run function in a thread using `thread.start(function)`, and in that function i call `humanizer.call_deferred("apply_clothes", HumanizerRegistry.clothes[clothing_name])`

**Comment by xand00** [comment]
I think i've used threads incorrectly, now it works without blocking main thread and my clothes change in about 3 seconds, i keep humanizer node in memory and reapply clothes on already loaded human

**Comment by matt-seaton** [comment]
We cannot load characters in a tpose.  We load the mesh from an obj file which is fixed in the a-pose.  There is no way to modify it.  I tried getting the character into a rest tpose.  Made no difference on animations.  Godot animation system doesn't care about rest pose, only base mesh.  Sadly they do not expose functionality to bake a posed mesh either for extracting new vertex positions, so we cannot convert the mesh into a tpose mesh.  I tried retargeting animation rotation tracks from apose to tpose and saving as a new animation library.  This node is in the authoring scene.  It is kind of close to working but still off a little bit.  You are welcome to try to get it working 100%.  I gave up.  I discuss this in the first 3 minutes of this video:

https://www.youtube.com/watch?v=1KakoCKkxh4&t=8s
